services:
  sparsemap-db:
    image: pgvector/pgvector:pg17 # 这里的标签保持 pg17
    container_name: sparsemap-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_DB: sparsemap_v1
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
